core:
  desired_distance: 1
  velocity:
    linear:
      maximum: 0.15
      coefficient: ~
    rotational:
      maximum: ~
      coefficient: 1.5
  frequency:
    interval: 5
    cmd_vel: 10
  target_fiducials:
    - 100
    - 101
robot:
  camera:
    horizontal_fov: 62.2
    vertical_fov: 48.8
    coordinate:
      x:
        coefficient: -1
        adjustment:
      y:
        coefficient: -1
        adjustment:
      z:
        coefficient: -1
        adjustment: