core:
  distance:
    desired: 1
    detection:
      trigger_base: 0.025
  buffer:
    movement:
      sec: 0
      nsec: 300000000
    detection:
      sec: 2
    search:
      sec: 4
  velocity:
    linear:
      maximum: 0.2
      coefficient: ~
    rotational:
      maximum: ~
      coefficient: 2
      buffer_coefficient: 0.5
  frequency:
    interval: 10
    cmd_vel: 10
    search_preempt: 10
    motion_detect: 5
    motion_detect_linger: 0
  size:
    detection_deque: 5
  target_fiducials:
    warm:
    - 100
    - 101
    cold:

robot:
  camera:
    horizontal_fov: 62.2
    vertical_fov: 48.8
    pose:
      orientation:
        x:
          coefficient: -1
          adjustment: ~
        y:
          coefficient: -1
          adjustment: ~
        z:
          coefficient: -1
          adjustment: ~

tf:
  frame_name:
    world: map
    robot: base_footprint
    camera: base_camera
    target: target
