core:
  distance:
    desired: 1
    detection:
      trigger: 0.007
  buffer:
    movement:
      sec: 0
      nsec: 300000000
    detection:
      sec: 2
    search:
      sec: 4
  velocity:
    linear:
      maximum: 0.15
      coefficient: ~
    rotational:
      maximum: ~
      coefficient: 2
      buffer_coefficient: 0.5
  frequency:
    interval: 10
    cmd_vel: 10
    search_preempt: 10
    motion_detect: 5
    motion_detect_linger: 5
  target_fiducials:
    warm:
    - 100
    - 101
    cold:

robot:
  camera:
    horizontal_fov: 62.2
    vertical_fov: 48.8
    pose:
      orientation:
        x:
          coefficient: -1
          adjustment:
        y:
          coefficient: -1
          adjustment:
        z:
          coefficient: -1
          adjustment:

tf:
  frame_name:
    robot: base_footprint
    target: target