core:
  desired_distance: 1
  time_buffer: 2
  velocity:
    linear:
      maximum: 0.15
      coefficient: ~
    rotational:
      maximum: ~
      coefficient: 2
      coefficient_buffer: 0.5
  frequency:
    interval: 10
    cmd_vel: 10
    search_preempt: 10
  target_fiducials:
    warm:
    - 100
    - 101
    cold:

robot:
  camera:
    horizontal_fov: 62.2
    vertical_fov: 48.8
    pose:
      orientation:
        x:
          coefficient: -1
          adjustment:
        y:
          coefficient: -1
          adjustment:
        z:
          coefficient: -1
          adjustment: